"""updated schema

Revision ID: dfd18b9aa6bc
Revises: 5cd55acb56da
Create Date: 2025-01-10 15:40:53.366077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dfd18b9aa6bc"
down_revision: Union[str, None] = "5cd55acb56da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS words CASCADE")
    op.drop_table("words")
    op.drop_table("users")
    op.drop_table("user_words")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_words",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("word_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_words_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
            name="user_words_word_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "word_id", name="user_words_pkey"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("tg_id", name="users_tg_id_key"),
        sa.UniqueConstraint("username", name="users_username_key"),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("word", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("pos", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("definition_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("voice_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("tg_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="words_pkey"),
        sa.UniqueConstraint("tg_id", name="words_tg_id_key"),
    )
    # ### end Alembic commands ###
